export type Unit = {
  id: number
  title: string
  shortTitle: string
  description: string
  topic: string
  level: "Beginner" | "Intermediate"
  duration: string
  icon: string
  accent: string
  vocabulary: string[]
  questions: string[]
  practiceExercises?: PracticeExercise[]
}

export type PracticeExercise = {
  id: string
  section: string
  instruction: string
  prompt: string
  options: string[]
  answer: string
  explanation: string
}

export const units: Unit[] = [
  {
    id: 1,
    title: "Unit 1: Family Life",
    shortTitle: "Family Life",
    description: "Talk about household chores, family roles, and sharing responsibilities.",
    topic: "Family life and household chores",
    level: "Beginner",
    duration: "20 min",
    icon: "🏠",
    accent: "bg-[#dc3e1d]",
    vocabulary: [
      "household chores",
      "homemaker",
      "breadwinner",
      "do the laundry",
      "do the washing-up",
      "put out the rubbish",
      "shop for groceries",
      "do the heavy lifting",
    ],
    questions: [
      "How does your family divide the household chores?",
      "Which household chore do you usually do, and how often?",
      "Should children help with housework? Why or why not?",
      "Describe one family routine that helps your family feel closer.",
    ],
    practiceExercises: [
      {
        id: "vocabulary-meaning-1",
        section: "Vocabulary · Match the meaning",
        instruction: "Choose the correct meaning of the word.",
        prompt: "breadwinner",
        options: [
          "A person who manages the home and often raises children",
          "Someone who earns money to support the family",
          "Work such as cooking, cleaning, or washing clothes",
          "Food and other goods bought at a shop",
        ],
        answer: "Someone who earns money to support the family",
        explanation: "A breadwinner is the person whose earnings support the family.",
      },
      {
        id: "vocabulary-meaning-2",
        section: "Vocabulary · Match the meaning",
        instruction: "Choose the correct meaning of the word.",
        prompt: "housework",
        options: [
          "Work such as cooking, cleaning, or washing clothes",
          "Picking up and carrying heavy objects",
          "Food and other goods bought at a shop",
          "Someone who earns money to support the family",
        ],
        answer: "Work such as cooking, cleaning, or washing clothes",
        explanation: "Housework means the jobs people do to take care of a home.",
      },
      {
        id: "vocabulary-meaning-3",
        section: "Vocabulary · Match the meaning",
        instruction: "Choose the correct meaning of the word.",
        prompt: "groceries",
        options: [
          "Picking up and carrying heavy objects",
          "A person who manages the home and often raises children",
          "Food and other goods bought at a shop or supermarket",
          "Work such as cooking, cleaning, or washing clothes",
        ],
        answer: "Food and other goods bought at a shop or supermarket",
        explanation: "Groceries are food and everyday goods bought from a shop or supermarket.",
      },
      {
        id: "vocabulary-meaning-4",
        section: "Vocabulary · Match the meaning",
        instruction: "Choose the correct meaning of the word.",
        prompt: "homemaker",
        options: [
          "Someone who earns money to support the family",
          "A person who manages the home and often raises children",
          "Picking up and carrying heavy objects",
          "Food and other goods bought at a shop",
        ],
        answer: "A person who manages the home and often raises children",
        explanation: "A homemaker manages the household and may care for the children.",
      },
      {
        id: "vocabulary-meaning-5",
        section: "Vocabulary · Match the meaning",
        instruction: "Choose the correct meaning of the phrase.",
        prompt: "heavy lifting",
        options: [
          "Picking up and carrying heavy objects",
          "Doing the weekly shopping",
          "Managing the family budget",
          "Washing clothes and dishes",
        ],
        answer: "Picking up and carrying heavy objects",
        explanation: "Heavy lifting means lifting or carrying objects that are heavy.",
      },
      {
        id: "vocabulary-sentence-1",
        section: "Vocabulary · Complete the sentence",
        instruction: "Choose the word or phrase that completes the sentence.",
        prompt: "My mother is a ________. She stays at home to look after the family.",
        options: ["homemaker", "breadwinner", "groceries", "heavy lifting", "housework"],
        answer: "homemaker",
        explanation: "A homemaker stays at home and manages family and household responsibilities.",
      },
      {
        id: "vocabulary-sentence-2",
        section: "Vocabulary · Complete the sentence",
        instruction: "Choose the word or phrase that completes the sentence.",
        prompt: "When I lived in this city, I used to shop for ________ at this supermarket.",
        options: ["homemaker", "breadwinner", "groceries", "heavy lifting", "housework"],
        answer: "groceries",
        explanation: "We use the collocation “shop for groceries.”",
      },
      {
        id: "vocabulary-sentence-3",
        section: "Vocabulary · Complete the sentence",
        instruction: "Choose the word or phrase that completes the sentence.",
        prompt: "My eldest son is strong enough to do the ________ for the family.",
        options: ["homemaker", "breadwinner", "groceries", "heavy lifting", "housework"],
        answer: "heavy lifting",
        explanation: "The adjective “strong” points to work that involves lifting heavy objects.",
      },
      {
        id: "vocabulary-sentence-4",
        section: "Vocabulary · Complete the sentence",
        instruction: "Choose the word or phrase that completes the sentence.",
        prompt: "Hanna hates doing ________ except cooking.",
        options: ["homemaker", "breadwinner", "groceries", "heavy lifting", "housework"],
        answer: "housework",
        explanation: "Cooking is one kind of housework.",
      },
      {
        id: "vocabulary-sentence-5",
        section: "Vocabulary · Complete the sentence",
        instruction: "Choose the word or phrase that completes the sentence.",
        prompt: "Mr Lewis is the ________ of the family, but he still helps with the housework.",
        options: ["homemaker", "breadwinner", "groceries", "heavy lifting", "housework"],
        answer: "breadwinner",
        explanation: "The breadwinner earns money to support the family.",
      },
      {
        id: "grammar-choice-1",
        section: "Grammar · Choose the verb form",
        instruction: "Choose the correct present-tense form.",
        prompt: "Mrs Lan usually ___ the cooking in her family.",
        options: ["does", "is doing"],
        answer: "does",
        explanation: "“Usually” describes a routine, so use the present simple.",
      },
      {
        id: "grammar-choice-2",
        section: "Grammar · Choose the verb form",
        instruction: "Choose the correct present-tense form.",
        prompt: "He cannot answer the phone now. He ___ the rubbish.",
        options: ["puts out", "is putting out"],
        answer: "is putting out",
        explanation: "“Now” signals an action happening at the moment, so use the present continuous.",
      },
      {
        id: "grammar-choice-3",
        section: "Grammar · Choose the verb form",
        instruction: "Choose the correct present-tense form.",
        prompt: "He ___ the house every day.",
        options: ["cleans", "is cleaning"],
        answer: "cleans",
        explanation: "“Every day” describes a habit, so use the present simple.",
      },
      {
        id: "grammar-choice-4",
        section: "Grammar · Choose the verb form",
        instruction: "Choose the correct present-tense form.",
        prompt: "My sister cannot do any housework today. She ___ for her exams.",
        options: ["studies", "is studying"],
        answer: "is studying",
        explanation: "“Today” describes a temporary situation here, so use the present continuous.",
      },
      {
        id: "grammar-choice-5",
        section: "Grammar · Choose the verb form",
        instruction: "Choose the correct present-tense form.",
        prompt: "My mother ___ the laundry twice a week.",
        options: ["does", "is doing"],
        answer: "does",
        explanation: "“Twice a week” describes a repeated routine, so use the present simple.",
      },
      {
        id: "grammar-passage-1",
        section: "Grammar · Mother’s Day passage",
        instruction: "Choose the correct form of the verb in brackets.",
        prompt: "Every day, Mrs Lam ___ most of the housework. (do)",
        options: ["does", "is doing", "do"],
        answer: "does",
        explanation: "“Every day” calls for the present simple, and Mrs Lam is third-person singular.",
      },
      {
        id: "grammar-passage-2",
        section: "Grammar · Mother’s Day passage",
        instruction: "Choose the correct form of the verb in brackets.",
        prompt: "But today is Mother’s Day, so Mrs Lam ___ any housework. (not do)",
        options: ["does not do", "is not doing", "not doing"],
        answer: "is not doing",
        explanation: "“Today” contrasts with her normal routine, so use the present continuous.",
      },
      {
        id: "grammar-passage-3",
        section: "Grammar · Mother’s Day passage",
        instruction: "Choose the correct form of the verb in brackets.",
        prompt: "At the moment, she ___ her favourite TV programme. (watch)",
        options: ["watches", "is watching", "watch"],
        answer: "is watching",
        explanation: "“At the moment” signals the present continuous.",
      },
      {
        id: "grammar-passage-4",
        section: "Grammar · Mother’s Day passage",
        instruction: "Choose the correct form of the verb in brackets.",
        prompt: "Her children ___ the cooking. (do)",
        options: ["do", "does", "are doing"],
        answer: "are doing",
        explanation: "The plural subject “children” takes “are,” and the activity is happening now.",
      },
      {
        id: "grammar-passage-5",
        section: "Grammar · Mother’s Day passage",
        instruction: "Choose the correct form of the verb in brackets.",
        prompt: "Her husband ___ the house. (tidy up)",
        options: ["tidies up", "is tidying up", "are tidying up"],
        answer: "is tidying up",
        explanation: "The singular subject “husband” takes “is,” and the action is happening now.",
      },
      {
        id: "grammar-passage-6",
        section: "Grammar · Mother’s Day passage",
        instruction: "Choose the correct form of the verb in brackets.",
        prompt: "Everybody ___ hard to make it a special day for Mrs Lam. (try)",
        options: ["tries", "is trying", "are trying"],
        answer: "is trying",
        explanation: "“Everybody” is grammatically singular, and the action is happening now.",
      },
    ],
  },
  {
    id: 2,
    title: "Unit 2: Humans and the Environment",
    shortTitle: "Humans and the Environment",
    description: "Discuss green living, environmental action, and future plans.",
    topic: "Green living and environmental protection",
    level: "Intermediate",
    duration: "25 min",
    icon: "🌱",
    accent: "bg-[#477a45]",
    vocabulary: [
      "household appliances",
      "energy",
      "carbon footprint",
      "litter",
      "eco-friendly",
      "green lifestyle",
      "raise awareness",
      "clean up",
      "set up a club",
      "reduce waste",
      "protect the environment",
    ],
    questions: [
      "What can students do to make their school greener?",
      "How can you reduce your carbon footprint at home?",
      "What is one environmental activity you are going to join?",
      "Why should people adopt a greener lifestyle?",
    ],
    practiceExercises: [
      {
        id: "unit-2-vocabulary-meaning-1",
        section: "Vocabulary · Match the meaning",
        instruction: "Choose the correct meaning of the phrase.",
        prompt: "household appliances",
        options: [
          "Devices such as fridges or TVs used in people’s homes",
          "Power used to provide heat and light",
          "Rubbish left in a public place",
          "Products that cause no harm to the environment",
        ],
        answer: "Devices such as fridges or TVs used in people’s homes",
        explanation: "Household appliances are electrical devices used at home, such as fridges and televisions.",
      },
      {
        id: "unit-2-vocabulary-meaning-2",
        section: "Vocabulary · Match the meaning",
        instruction: "Choose the correct meaning of the word.",
        prompt: "energy",
        options: [
          "The amount of carbon dioxide an activity produces",
          "Power used for machines, heat, or light",
          "Rubbish left in a public place",
          "A device used in the home",
        ],
        answer: "Power used for machines, heat, or light",
        explanation: "Energy is the power used to run machines or provide heat and light.",
      },
      {
        id: "unit-2-vocabulary-meaning-3",
        section: "Vocabulary · Match the meaning",
        instruction: "Choose the correct meaning of the phrase.",
        prompt: "carbon footprint",
        options: [
          "The amount of carbon dioxide produced by a person or organisation",
          "Power obtained only from the sun",
          "Waste collected for recycling",
          "A machine that measures air quality",
        ],
        answer: "The amount of carbon dioxide produced by a person or organisation",
        explanation: "A carbon footprint measures the greenhouse-gas impact of activities.",
      },
      {
        id: "unit-2-vocabulary-meaning-4",
        section: "Vocabulary · Match the meaning",
        instruction: "Choose the correct meaning of the word.",
        prompt: "litter",
        options: [
          "Rubbish left in an open or public place",
          "Objects prepared for recycling",
          "Electricity used by a household",
          "Polluted water from a factory",
        ],
        answer: "Rubbish left in an open or public place",
        explanation: "Litter is rubbish that has been dropped and left in a public place.",
      },
      {
        id: "unit-2-vocabulary-meaning-5",
        section: "Vocabulary · Match the meaning",
        instruction: "Choose the correct meaning of the adjective.",
        prompt: "eco-friendly",
        options: [
          "Causing little or no harm to the environment",
          "Using a large amount of electricity",
          "Made only for household use",
          "Producing carbon dioxide quickly",
        ],
        answer: "Causing little or no harm to the environment",
        explanation: "Eco-friendly products and actions are designed to avoid environmental harm.",
      },
      {
        id: "unit-2-vocabulary-sentence-1",
        section: "Vocabulary · Complete the sentence",
        instruction: "Choose the word or phrase that completes the sentence.",
        prompt: "________ car models always attract attention at exhibitions.",
        options: ["Eco-friendly", "Household appliances", "Carbon footprint", "Litter", "Energy"],
        answer: "Eco-friendly",
        explanation: "“Eco-friendly” is an adjective that can describe car models that cause less environmental harm.",
      },
      {
        id: "unit-2-vocabulary-sentence-2",
        section: "Vocabulary · Complete the sentence",
        instruction: "Choose the word or phrase that completes the sentence.",
        prompt: "Remember to turn off your ________ when they are not being used.",
        options: ["eco-friendly", "household appliances", "carbon footprint", "litter", "energy"],
        answer: "household appliances",
        explanation: "Devices such as televisions and lights should be turned off when they are not in use.",
      },
      {
        id: "unit-2-vocabulary-sentence-3",
        section: "Vocabulary · Complete the sentence",
        instruction: "Choose the word or phrase that completes the sentence.",
        prompt: "Small changes in your daily habits can help reduce the ________ you produce.",
        options: ["eco-friendly", "household appliances", "carbon footprint", "litter", "energy"],
        answer: "carbon footprint",
        explanation: "Changing daily habits can reduce the carbon emissions connected with your activities.",
      },
      {
        id: "unit-2-vocabulary-sentence-4",
        section: "Vocabulary · Complete the sentence",
        instruction: "Choose the word or phrase that completes the sentence.",
        prompt: "One of the most important sources of ________ is the sun.",
        options: ["eco-friendly", "household appliances", "carbon footprint", "litter", "energy"],
        answer: "energy",
        explanation: "The sun is a major renewable source of energy.",
      },
      {
        id: "unit-2-vocabulary-sentence-5",
        section: "Vocabulary · Complete the sentence",
        instruction: "Choose the word or phrase that completes the sentence.",
        prompt: "Students are reminded to pick up ________ that they see on the ground.",
        options: ["eco-friendly", "household appliances", "carbon footprint", "litter", "energy"],
        answer: "litter",
        explanation: "We use the collocation “pick up litter.”",
      },
      {
        id: "unit-2-future-form-1",
        section: "Grammar · Future forms",
        instruction: "Choose “will” or the correct form of “be going to.”",
        prompt: "I do not think she ___ come tonight. She has to revise for tomorrow’s exam.",
        options: ["will", "is going to", "is"],
        answer: "will",
        explanation: "Use “will” for a prediction based on what you think or believe.",
      },
      {
        id: "unit-2-future-form-2",
        section: "Grammar · Future forms",
        instruction: "Choose “will” or the correct form of “be going to.”",
        prompt: "We have already made the decision. We ___ buy a new house next month.",
        options: ["will", "are going to", "is going to"],
        answer: "are going to",
        explanation: "Use “be going to” for a plan decided before the moment of speaking.",
      },
      {
        id: "unit-2-future-form-3",
        section: "Grammar · Future forms",
        instruction: "Choose “will” or the correct form of “be going to.”",
        prompt: "I am sure she ___ pass the final exam.",
        options: ["will", "is going to", "does"],
        answer: "will",
        explanation: "“I am sure” introduces a belief or prediction, so use “will.”",
      },
      {
        id: "unit-2-future-form-4",
        section: "Grammar · Future forms",
        instruction: "Choose “will” or the correct form of “be going to.”",
        prompt: "Look at the sun. It ___ be a beautiful day.",
        options: ["will", "is going to", "are going to"],
        answer: "is going to",
        explanation: "Use “be going to” for a prediction based on present evidence.",
      },
      {
        id: "unit-2-future-form-5",
        section: "Grammar · Future forms",
        instruction: "Choose “will” or the correct form of “be going to.”",
        prompt: "I forgot to phone Dad. I ___ do it right after lunch.",
        options: ["will", "am going to", "am"],
        answer: "will",
        explanation: "Use “will” for a decision made at the moment of speaking.",
      },
      {
        id: "unit-2-passive-voice-1",
        section: "Grammar · Passive voice",
        instruction: "Choose the correct passive form of the sentence.",
        prompt: "More and more people adopt a green lifestyle.",
        options: [
          "A green lifestyle is adopted by more and more people.",
          "A green lifestyle was adopted by more and more people.",
          "More and more people are adopted by a green lifestyle.",
        ],
        answer: "A green lifestyle is adopted by more and more people.",
        explanation: "The present-simple passive is “am/is/are + past participle.”",
      },
      {
        id: "unit-2-passive-voice-2",
        section: "Grammar · Passive voice",
        instruction: "Choose the correct passive form of the sentence.",
        prompt: "The students did not put the rubbish in the bins after the party yesterday.",
        options: [
          "The rubbish was not put in the bins after the party yesterday.",
          "The rubbish is not put in the bins after the party yesterday.",
          "The rubbish did not put in the bins after the party yesterday.",
        ],
        answer: "The rubbish was not put in the bins after the party yesterday.",
        explanation: "The past-simple passive is “was/were + past participle”; the past participle of “put” is “put.”",
      },
      {
        id: "unit-2-passive-voice-3",
        section: "Grammar · Passive voice",
        instruction: "Choose the correct passive form of the sentence.",
        prompt: "We will plant more trees in the neighbourhood.",
        options: [
          "More trees will be planted in the neighbourhood.",
          "More trees are planted in the neighbourhood.",
          "More trees will plant in the neighbourhood.",
        ],
        answer: "More trees will be planted in the neighbourhood.",
        explanation: "The future passive is “will be + past participle.”",
      },
      {
        id: "unit-2-passive-voice-4",
        section: "Grammar · Passive voice",
        instruction: "Choose the correct passive form of the sentence.",
        prompt: "Our club is going to organise many clean-up activities this weekend.",
        options: [
          "Many clean-up activities are going to be organised this weekend.",
          "Many clean-up activities will organise this weekend.",
          "Many clean-up activities are going to organise this weekend.",
        ],
        answer: "Many clean-up activities are going to be organised this weekend.",
        explanation: "The passive form is “am/is/are going to be + past participle.”",
      },
      {
        id: "unit-2-passive-voice-5",
        section: "Grammar · Passive voice",
        instruction: "Choose the correct passive form of the sentence.",
        prompt: "They discussed important environmental issues at the meeting.",
        options: [
          "Important environmental issues were discussed at the meeting.",
          "Important environmental issues are discussed at the meeting.",
          "Important environmental issues discussed at the meeting.",
        ],
        answer: "Important environmental issues were discussed at the meeting.",
        explanation: "The original verb is past simple, so use “were + discussed” in the passive.",
      },
    ],
  },
  {
    id: 3,
    title: "Unit 3: Music",
    shortTitle: "Music",
    description: "Talk about artists, musical ability, performances, and sharing music online.",
    topic: "Music and talented artists",
    level: "Intermediate",
    duration: "20 min",
    icon: "🎵",
    accent: "bg-[#7254a3]",
    vocabulary: [
      "perform",
      "judge",
      "audience",
      "talented",
      "single",
      "pop singer",
      "teen idol",
      "talented artist",
      "musical instrument",
      "cover song",
      "social media",
      "receive an award",
    ],
    questions: [
      "Who is your favourite singer or musician, and why?",
      "Which musical instrument would you like to learn?",
      "How can social media help a young artist become popular?",
      "Describe a talented artist you admire.",
    ],
    practiceExercises: [
      {
        id: "unit-3-vocabulary-meaning-1",
        section: "Vocabulary · Match the meaning",
        instruction: "Choose the correct meaning of the word.",
        prompt: "perform",
        options: [
          "To sing, dance, or play music for an audience",
          "To decide the result of a competition",
          "To record one new song",
          "To watch a live concert",
        ],
        answer: "To sing, dance, or play music for an audience",
        explanation: "To perform means to entertain people by singing, dancing, acting, or playing music.",
      },
      {
        id: "unit-3-vocabulary-meaning-2",
        section: "Vocabulary · Match the meaning",
        instruction: "Choose the correct meaning of the noun.",
        prompt: "judge",
        options: [
          "A person who decides the results of a competition",
          "A person who watches a performance",
          "A musician with a natural ability",
          "A person who organises a concert",
        ],
        answer: "A person who decides the results of a competition",
        explanation: "In a competition, a judge evaluates performances and helps decide the result.",
      },
      {
        id: "unit-3-vocabulary-meaning-3",
        section: "Vocabulary · Match the meaning",
        instruction: "Choose the correct meaning of the noun.",
        prompt: "audience",
        options: [
          "The people who watch or listen to a performance or programme",
          "The musicians who play together",
          "The people who decide a competition result",
          "The songs on a music album",
        ],
        answer: "The people who watch or listen to a performance or programme",
        explanation: "An audience is the group of people watching or listening to the same performance or programme.",
      },
      {
        id: "unit-3-vocabulary-meaning-4",
        section: "Vocabulary · Match the meaning",
        instruction: "Choose the correct meaning of the adjective.",
        prompt: "talented",
        options: [
          "Having a natural ability to do something well",
          "Being famous on social media",
          "Having performed for many years",
          "Being interested in music competitions",
        ],
        answer: "Having a natural ability to do something well",
        explanation: "A talented person has a natural ability or skill in a particular activity.",
      },
      {
        id: "unit-3-vocabulary-meaning-5",
        section: "Vocabulary · Match the meaning",
        instruction: "Choose the correct meaning of the noun.",
        prompt: "single",
        options: [
          "A music release containing one main song",
          "A live performance by one artist",
          "A singing competition on television",
          "A person who performs alone",
        ],
        answer: "A music release containing one main song",
        explanation: "In music, a single is a recording released with one main song.",
      },
      {
        id: "unit-3-vocabulary-sentence-1",
        section: "Vocabulary · Complete the sentence",
        instruction: "Choose the word that completes the sentence.",
        prompt: "He has a nice voice, and he is a ________ musician.",
        options: ["talented", "audience", "single", "judge", "perform"],
        answer: "talented",
        explanation: "“Talented” is an adjective describing a musician with natural ability.",
      },
      {
        id: "unit-3-vocabulary-sentence-2",
        section: "Vocabulary · Complete the sentence",
        instruction: "Choose the word that completes the sentence.",
        prompt: "The TV show attracted an ________ of more than five million.",
        options: ["talented", "audience", "single", "judge", "perform"],
        answer: "audience",
        explanation: "An audience is the group of people who watch a programme.",
      },
      {
        id: "unit-3-vocabulary-sentence-3",
        section: "Vocabulary · Complete the sentence",
        instruction: "Choose the word that completes the sentence.",
        prompt: "Have you heard their new ________?",
        options: ["talented", "audience", "single", "judge", "perform"],
        answer: "single",
        explanation: "A newly released song can be called a new single.",
      },
      {
        id: "unit-3-vocabulary-sentence-4",
        section: "Vocabulary · Complete the sentence",
        instruction: "Choose the word that completes the sentence.",
        prompt: "She was invited to be a ________ on a popular TV talent show.",
        options: ["talented", "audience", "single", "judge", "perform"],
        answer: "judge",
        explanation: "A judge evaluates the contestants and helps decide the result.",
      },
      {
        id: "unit-3-vocabulary-sentence-5",
        section: "Vocabulary · Complete the sentence",
        instruction: "Choose the word that completes the sentence.",
        prompt: "Many famous artists decided to ________ at the charity concert.",
        options: ["talented", "audience", "single", "judge", "perform"],
        answer: "perform",
        explanation: "After “decided to,” use the base verb “perform.”",
      },
      {
        id: "unit-3-conjunction-1",
        section: "Grammar · Compound sentences",
        instruction: "Choose the conjunction that correctly joins the ideas.",
        prompt: "I am a jazz fan, ___ my favourite style is from the late 1960s.",
        options: ["and", "but", "or", "so"],
        answer: "and",
        explanation: "“And” connects two related, compatible ideas.",
      },
      {
        id: "unit-3-conjunction-2",
        section: "Grammar · Compound sentences",
        instruction: "Choose the conjunction that correctly joins the ideas.",
        prompt: "Jackson wants to attend the music festival on Saturday, ___ he has a maths exam that day.",
        options: ["and", "but", "or", "so"],
        answer: "but",
        explanation: "“But” expresses the contrast between his wish and the conflicting exam.",
      },
      {
        id: "unit-3-conjunction-3",
        section: "Grammar · Compound sentences",
        instruction: "Choose the conjunction that correctly joins the ideas.",
        prompt: "You can book the tickets online, ___ you can buy them at the stadium ticket office.",
        options: ["and", "but", "or", "so"],
        answer: "or",
        explanation: "“Or” presents two alternative ways to buy tickets.",
      },
      {
        id: "unit-3-conjunction-4",
        section: "Grammar · Compound sentences",
        instruction: "Choose the conjunction that correctly joins the ideas.",
        prompt: "The concert did not happen, ___ we stayed at home.",
        options: ["and", "but", "or", "so"],
        answer: "so",
        explanation: "“So” introduces the result of the concert being cancelled.",
      },
      {
        id: "unit-3-infinitive-1",
        section: "Grammar · Infinitive forms",
        instruction: "Choose the correct form of the verb in brackets.",
        prompt: "Her fans planned ___ her a surprise present on her birthday. (send)",
        options: ["to send", "send", "sending"],
        answer: "to send",
        explanation: "Use “plan + to-infinitive”: plan to send.",
      },
      {
        id: "unit-3-infinitive-2",
        section: "Grammar · Infinitive forms",
        instruction: "Choose the correct form of the verb in brackets.",
        prompt: "Their performance was so boring that it made us ___ asleep. (fall)",
        options: ["to fall", "fall", "falling"],
        answer: "fall",
        explanation: "Use the bare infinitive after “make + object”: made us fall.",
      },
      {
        id: "unit-3-infinitive-3",
        section: "Grammar · Infinitive forms",
        instruction: "Choose the correct form of the verb in brackets.",
        prompt: "Because of the bad weather, the band decided ___ its live concert. (delay)",
        options: ["to delay", "delay", "delaying"],
        answer: "to delay",
        explanation: "Use “decide + to-infinitive”: decided to delay.",
      },
      {
        id: "unit-3-infinitive-4",
        section: "Grammar · Infinitive forms",
        instruction: "Choose the correct form of the verb in brackets.",
        prompt: "Her parents will not let her ___ such TV shows. (watch)",
        options: ["to watch", "watch", "watching"],
        answer: "watch",
        explanation: "Use the bare infinitive after “let + object”: let her watch.",
      },
    ],
  },
]

export function getUnit(id: number) {
  return units.find((unit) => unit.id === id)
}
